Don't cast an initializer to the struct type in power_insn_available.c.
In C99 mode casting the initializer to the struct type will cause gcc
to report an error like:
power_insn_available.c:38:1: error: initializer element is not constant

Simply removing the unnecessary cast fixes this (and is also valid C90).