docs/xml/FAQ.xml: Replace mempools xref with ulink
The FAQ.xml should not xref other parts of the docs, because it is
built standalone as FAQ.txt.

ERROR: xref linking to mc-manual.mempools has no generated link text.
Error: no ID for constraint linkend: "mc-manual.mempools".
XLink to nonexistent id: mc-manual.mempools

So replace the xref with an ulink with an url to the online copy of
the manual.