s390x: Testcase workaround
GCC 14.2.0 does not recognize convert to fixed/logical opcodes:

bfp-convert.c: Assembler messages:
bfp-convert.c:205: Error: Unrecognized opcode: `cfebra'
bfp-convert.c:210: Error: Unrecognized opcode: `cgebra'
...
bfp-convert.c:314: Error: Unrecognized opcode: `clfebr'
bfp-convert.c:314: Error: Unrecognized opcode: `clgebr'
...