riscv64: Avoid warning about missing return value in stat wrapper
m_libcfile.c: In function 'vgPlain_stat':
m_libcfile.c:594:1: error: control reaches end of non-void function [-Werror=return-type]
  594 | }
      | ^